fix: same values but different casing creates conflicting enums (#1259)
Enums in schema which has same value but different casing creates same
enum values which conflicts with each other. For instance,
[observed](https://github.com/cdk8s-team/cdk8s-cli/issues/578#issuecomment-1559646717)
while importing a custom resource definition in cdk8s.

```
\| 1086   REPLACE = 'replace',
--
\|        ~~~~~~~
\| com.coreos.monitoring.ts:1088:3 - error TS2300: Duplicate identifier 'REPLACE'.
\| 1088   REPLACE = 'Replace',
\|        ~~~~~~~
\| com.coreos.monitoring.ts:1090:3 - error TS2300: Duplicate identifier 'KEEP'.
\| 1090   KEEP = 'keep',
\|        ~~~~
\| com.coreos.monitoring.ts:1092:3 - error TS2300: Duplicate identifier 'KEEP'.
\| 1092   KEEP = 'Keep',
\|        ~~~~
\| com.coreos.monitoring.ts:1094:3 - error TS2300: Duplicate identifier 'DROP'.
\| 1094   DROP = 'drop',
\|        ~~~~
\| com.coreos.monitoring.ts:1096:3 - error TS2300: Duplicate identifier 'DROP'.
\| 1096   DROP = 'Drop',
```

Fixes https://github.com/cdk8s-team/cdk8s-cli/issues/578

---------

Signed-off-by: Vinayak Kukreja <vinakuk@amazon.com>